name = "omnidrive-api"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = [ "nodejs_compat_v2" ]

[triggers]
crons = ["*/30 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "omnidrive"
database_id = "ba3f31b2-a9b6-4268-9c94-ca567a469ecb"

[[kv_namespaces]]
binding = "KV"
id = "9b589c9bea784a0ab6928c210c789b7b"

[vars]
FRONTEND_URL = "https://omnidrive.pages.dev"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
